name: delivery_app_test
description: Test Flutter Delivery App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  shared_preferences: ^2.0.18
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  transparent_image: ^2.0.1
  intl: ^0.18.1
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
       - asset: assets/fonts/SFProDisplay-Regular.ttf
         weight: 400
       - asset: assets/fonts/SFProDisplay-Medium.ttf
         weight: 500